# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit article.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(akc)
library(knitr)


## ----fig1, out.width = "100%", out.height = "30%", fig.cap = "The design of akc framework."----
knitr::include_graphics("fig1.png")


## ----fig2, out.width = "100%", out.height = "30%", fig.cap = "An example of keyword extraction procedure (the letters are automatically turned to lower case in sentence division)."----
knitr::include_graphics("fig2.png")


## ----fig3, out.width = "100%", out.height = "25%", fig.cap = "An example of keyword merging conversion rule applied in akc. The keywords with the same lemma (or stem) would be merged to the highest frequency keyword in the original form."----
knitr::include_graphics("fig3.png")


## ---- echo=TRUE---------------------------------------------------------------
library(akc)
rj_bib = readRDS("./rj_bib.rds")
rj_bib


## ---- echo=TRUE---------------------------------------------------------------
rj_user_dict = readRDS("./rj_user_dict.rds")
rj_user_dict


## ----echo=TRUE----------------------------------------------------------------
rj_dict = make_dict(rj_user_dict$keyword)


## ----echo=TRUE----------------------------------------------------------------
rj_extract_keywords = rj_bib %>% 
  keyword_extract(id = "id",text = "abstract",dict = rj_dict)


## ----echo=TRUE----------------------------------------------------------------
rj_cleaned_keywords = rj_extract_keywords %>% 
  keyword_clean() %>% 
  keyword_merge()


## ----echo=TRUE----------------------------------------------------------------
rj_network = rj_cleaned_keywords %>% 
  keyword_group()


## ----fig4,echo=TRUE,fig.cap="Network visualization provided by akc.",fig.align='center'----
rj_network %>% 
  keyword_vis()


## ----fig5,echo=TRUE,fig.cap="Focus on one cluster (Group 1) of the network.",fig.align='center'----
rj_network %>% 
  keyword_network(group_no = 1,max_nodes = 20) 


## ----table1,echo=TRUE---------------------------------------------------------
rj_table = rj_network %>% 
  keyword_table() 


## ----tab1-1, eval = knitr::is_html_output(), layout = "l-body-outset"---------
#> knitr::kable(rj_table, format = "html", caption = "Informative table exported by akc.",align = "c")%>%
#>   kableExtra::kable_styling(position = "center") %>%
#>   kableExtra::column_spec(2, width = "16cm")


## ----tab1-2, eval = knitr::is_latex_output()----------------------------------
knitr::kable(rj_table, format = "latex", caption = "Informative table exported by akc.",align = "c") %>% 
  kableExtra::kable_styling(font_size = 7) %>%
  kableExtra::column_spec(2, width = "10cm")

